# Generated by Django 4.2 on 2023-04-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pkd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkdNumber', models.CharField(max_length=255)),
                ('pkdDesc', models.CharField(max_length=255)),
            ],
        ),
    ]
